language: python
python:
  - "3.6"
node_js:
  - "10"

dist: trusty
sudo: required

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - TESTS=user
    - TESTS=document

notifications:
  webhooks:
    - https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN

addons:
  sauce_connect:
    no_ssl_bump_domains: all

before_install:
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPWZpZHVz`
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9OWU5ZGJkNzctNDIwOC00ODM5LTkwY2ItMTZkM2M5ODUxZGMw`

install:
  - mv travis/configuration.py ./
  - pip3 install requests[security]
  - pip3 install -r requirements.txt
  - pip3 install -r dev-requirements.txt
  - flake8 ./
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install selenium
  - coverage run manage.py init --no-static --no-compress
  - ./manage.py check_js

script:
  - travis_retry coverage run manage.py test $TESTS

after_success:
  - coverage report
  - coveralls

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
    - static-libs
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
