language: node_js
python:
  - "2.7"
node_js:
  - "6"

dist: trusty

env:
  - TRAVIS_PYTHON_VERSION="2.7"

addons:
  sauce_connect:
    no_ssl_bump_domains: all

before_install:
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPWZpZHVz`
  - x="bas";`"$x"e64 -d <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9OWU5ZGJkNzctNDIwOC00ODM5LTkwY2ItMTZkM2M5ODUxZGMw`

install:
  - mv travis/configuration.py ./
  - pip install --user requests[security]
  - pip install --user -r requirements.txt
  - pip install --user -r dev-requirements.txt
  - flake8 ./
  - pip install --user coverage
  - pip install --user coveralls
  - pip install --user selenium
  - coverage run manage.py init --no-static --no-compress
  - ./manage.py check_js

script:
  - travis_retry coverage run manage.py test

after_success:
  - coverage report
  - coveralls

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
    - static-libs
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
